# Generated by Django 4.2.7 on 2023-11-24 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=movies.models.user_directory_path)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('animation', 'Animation'), ('comedy', 'Comedy'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('family', 'Family'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('thriller', 'Thriller')], max_length=100)),
                ('director', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=255)),
                ('date_rated', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_movie', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
